language: php
php:
    - '7.0'
env:
    - DB=mysql

cache:
    directories:
        - $HOME/.composer/cache

# when triggered by a push only build master branch and do deployment
# other branches are built via pr
branches:
  only:
    - master

install:
    # Variable is empty when building a push. As this only happens on master, set it preemptively
    - if [ -z $TRAVIS_PULL_REQUEST_BRANCH ]; then export TRAVIS_PULL_REQUEST_BRANCH="master"; fi
    - cd ..
    - git clone https://github.com/neos/flow-base-distribution.git -b 4.0
    - cd flow-base-distribution
    - composer config repositories.github vcs https://github.com/PalatinCoder/SquadIT.WebApp.git
    - composer require squadit/webapp:dev-$TRAVIS_PULL_REQUEST_BRANCH
    - composer remove neos/welcome
    - rm -rf Packages/Application/SquadIT.WebApp
    - mv ../SquadIT.WebApp Packages/Application/SquadIT.WebApp
    - composer install -d Build/Behat
    - composer require -d Build/Behat satooshi/php-coveralls

before_script:
  - echo 'date.timezone = "Antarctica/Troll"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'opcache.fast_shutdown = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'opcache.enable_cli = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'zend.enable_gc = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'report_zend_debug = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'report_memleaks = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/
  - if [ -f Configuration/Routes.yaml ]; then rm Configuration/Routes.yaml; fi
  - FLOW_CONTEXT=Development/Behat ./flow server:run &

script:
    # TODO Unit & Functional Tests
    - ./bin/phpunit --colors --stop-on-failure -c Packages/Application/SquadIT.WebApp/Tests/UnitTests.xml
    - ./bin/behat --ansi --stop-on-failure -f progress,failed -c Packages/Application/SquadIT.WebApp/Tests/Behavior/behat.yml --tags ~@skip

after_success:
  - cd Packages/Application/SquadIT.WebApp
  - travis_retry php ../../../bin/coveralls -v

deploy:
    provider: script
    script: curl https://squadit-service.jan-sl.de/travis-ci/deploy.sh
    on:
        branch: master
