language: php
php:
    - '7.0'
cache:
    directories:
        - $HOME/.composer/cache

install:
    - phpenv config-rm xdebug.ini
    - cd ..
    - composer create-project neos/flow-base-distribution --no-progress --no-interaction
    - cd flow-base-distribution
    - mv ../SquadIT.WebApp Packages/Application/

before_script:
  - echo 'date.timezone = "Antarctica/Troll"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'opcache.fast_shutdown = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'opcache.enable_cli = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'zend.enable_gc = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'report_zend_debug = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'report_memleaks = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install -d Build/Behat
  # TODO setup database, config and routing
  # but for now it works ;)

script:
    # TODO Unit & Functional Tests
    - FLOW_CONTEXT=Testing/Behat
    - ./bin/behat --ansi --stop-on-failure -f progress -c Packages/Application/SquadIT.WebApp/Tests/Behavior/behat.yml

deploy:
    provider: script
    script: curl https://squadit-service.jan-sl.de/travis-ci/deploy.sh
    on:
        branch: master
