<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20161210112406 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE squadit_webapp_domain_model_squad_members_join (webapp_squad VARCHAR(40) NOT NULL, webapp_user VARCHAR(40) NOT NULL, INDEX IDX_BF57B404209C26A7 (webapp_squad), INDEX IDX_BF57B404145ABC0A (webapp_user), PRIMARY KEY(webapp_squad, webapp_user)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE squadit_webapp_domain_model_squad_members_join ADD CONSTRAINT FK_BF57B404209C26A7 FOREIGN KEY (webapp_squad) REFERENCES squadit_webapp_domain_model_squad (persistence_object_identifier)');
        $this->addSql('ALTER TABLE squadit_webapp_domain_model_squad_members_join ADD CONSTRAINT FK_BF57B404145ABC0A FOREIGN KEY (webapp_user) REFERENCES squadit_webapp_domain_model_user (persistence_object_identifier)');
        $this->addSql('CREATE UNIQUE INDEX flow_identity_squadit_webapp_domain_model_squad ON squadit_webapp_domain_model_squad (name)');
        $this->addSql('ALTER TABLE squadit_webapp_domain_model_user DROP FOREIGN KEY FK_7FD23F7DCFD0FFE7');
        $this->addSql('DROP INDEX IDX_7FD23F7DCFD0FFE7 ON squadit_webapp_domain_model_user');
        $this->addSql('ALTER TABLE squadit_webapp_domain_model_user DROP squad');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('DROP TABLE squadit_webapp_domain_model_squad_members_join');
        $this->addSql('DROP INDEX flow_identity_squadit_webapp_domain_model_squad ON squadit_webapp_domain_model_squad');
        $this->addSql('ALTER TABLE squadit_webapp_domain_model_user ADD squad VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE squadit_webapp_domain_model_user ADD CONSTRAINT FK_7FD23F7DCFD0FFE7 FOREIGN KEY (squad) REFERENCES squadit_webapp_domain_model_squad (persistence_object_identifier)');
        $this->addSql('CREATE INDEX IDX_7FD23F7DCFD0FFE7 ON squadit_webapp_domain_model_user (squad)');
    }
}
