<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20161129090407 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return 'Create user and squad model';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE squadit_webapp_domain_model_squad (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(80) NOT NULL, description VARCHAR(255) DEFAULT NULL, picture VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE squadit_webapp_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, squad VARCHAR(40) DEFAULT NULL, account VARCHAR(40) DEFAULT NULL, firstname VARCHAR(80) NOT NULL, lastname VARCHAR(80) NOT NULL, profilepicture VARCHAR(255) DEFAULT NULL, INDEX IDX_7FD23F7DCFD0FFE7 (squad), UNIQUE INDEX UNIQ_7FD23F7D7D3656A4 (account), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE squadit_webapp_domain_model_user ADD CONSTRAINT FK_7FD23F7DCFD0FFE7 FOREIGN KEY (squad) REFERENCES squadit_webapp_domain_model_squad (persistence_object_identifier)');
        $this->addSql('ALTER TABLE squadit_webapp_domain_model_user ADD CONSTRAINT FK_7FD23F7D7D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE squadit_webapp_domain_model_user DROP FOREIGN KEY FK_7FD23F7D7D3656A4');
        $this->addSql('ALTER TABLE squadit_webapp_domain_model_user DROP FOREIGN KEY FK_7FD23F7DCFD0FFE7');
        $this->addSql('DROP TABLE squadit_webapp_domain_model_squad');
        $this->addSql('DROP TABLE squadit_webapp_domain_model_user');
    }
}
