-
  name: 'Landing Route'
  uriPattern: ''
  defaults:
    '@controller': 'Standard'
    '@action': 'index'
    '@package': 'SquadIT.WebApp'
    '@format': 'html'
-
  name: 'Squalendar'
  uriPattern: 'squad/{squad}/squalendar/{@action}'
  defaults:
    '@package': 'SquadIT.WebApp'
    '@controller': 'Event'
    '@action': 'index'
    '@format': 'html'
  routeParts:
    squad:
      objectType: 'SquadIT\WebApp\Domain\Model\Squad'
-
  name: 'Event Management'
  uriPattern: 'event/{event}/{@action}'
  defaults:
    '@package': 'SquadIT.WebApp'
    '@format': 'html'
    '@controller': 'Event'
  routeParts:
    event:
      objectType: 'SquadIT\WebApp\Domain\Model\Event'
-
  name: 'Squad Management'
  uriPattern: 'squad/{squad}/{@action}'
  defaults:
    '@package': 'SquadIT.WebApp'
    '@controller': 'Squad'
    '@format': 'html'
  routeParts:
    squad:
      objectType: 'SquadIT\WebApp\Domain\Model\Squad'
-
  name: 'Default Route'
  uriPattern: '{@controller}/{@action}'
  defaults:
    '@package': 'SquadIT.WebApp'
    '@format': 'html'
  appendExceedingArguments: true
