-
  name: 'Landing Route'
  uriPattern: ''
  defaults:
    '@controller': 'Standard'
    '@action': 'index'
    '@package': 'SquadIT.WebApp'
-
  name: 'Default Route'
  uriPattern: '{@controller}/{@action}'
  defaults:
    '@package': 'SquadIT.WebApp'
